/*
 * Copyright (c) 2019-2026 Tony Ho / Chuntung Ho. Some rights reserved.
 */

package com.chuntung.plugin.mybatis.builder.generator;

import com.chuntung.plugin.mybatis.builder.util.StringUtil;
import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.MyBatisGenerator;
import org.mybatis.generator.api.dom.OutputUtilities;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;
import org.mybatis.generator.config.MergeConstants;
import org.mybatis.generator.internal.DefaultCommentGenerator;

import java.sql.Types;
import java.util.Properties;
import java.util.Set;

import static org.mybatis.generator.internal.util.StringUtility.isTrue;

/**
 * Extends MBG's {@link DefaultCommentGenerator} so the @Generated merge markers (stamped on every
 * generated member, fields included) are inherited untouched, while appending the column details
 * (type, length, default value, remark) into the field's @Generated {@code comments} attribute.
 *
 * @author Tony Ho
 */
public class CustomCommentGenerator extends DefaultCommentGenerator {
    public static final String ADD_DATABASE_REMARK = "addDatabaseRemark";

    private static final FullyQualifiedJavaType GENERATED_IMPORT =
            new FullyQualifiedJavaType("jakarta.annotation.Generated");

    private boolean addDatabaseRemark;

    @Override
    public void addConfigurationProperties(Properties properties) {
        super.addConfigurationProperties(properties);
        addDatabaseRemark = isTrue(properties.getProperty(ADD_DATABASE_REMARK));
    }

    @Override
    public void addComment(XmlElement xmlElement) {
        // Keep the @mbg.generated tag the XML merger keys on, but brand the notice as MyBatis Builder.
        xmlElement.addElement(new TextElement("<!--"));
        xmlElement.addElement(new TextElement(OutputUtilities.xmlIndent(1)
                + "Generated Code - " + MergeConstants.NEW_ELEMENT_TAG));
        xmlElement.addElement(new TextElement(OutputUtilities.xmlIndent(1)
                + "This element is automatically generated by MyBatis Builder, do not modify."));
        xmlElement.addElement(new TextElement("-->"));
    }

    @Override
    public void addFieldAnnotation(Field field, IntrospectedTable introspectedTable,
                                   IntrospectedColumn introspectedColumn, Set<FullyQualifiedJavaType> imports) {
        if (!addDatabaseRemark) {
            super.addFieldAnnotation(field, introspectedTable, introspectedColumn, imports);
            return;
        }

        // Build a @Generated annotation whose value still matches MyBatisGenerator (so the merger keys
        // on it) but whose comments carry the column details that used to live in a Javadoc block.
        imports.add(GENERATED_IMPORT);
        field.addAnnotation(buildGeneratedAnnotation(buildColumnComment(introspectedTable, introspectedColumn)));
    }

    private String buildGeneratedAnnotation(String comment) {
        return "@Generated(value=\"" + MyBatisGenerator.class.getName()
                + "\", comments=\"" + escape(comment) + "\")";
    }

    private String buildColumnComment(IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn) {
        StringBuilder sb = new StringBuilder("Source field: ");
        sb.append(introspectedTable.getFullyQualifiedTable()).append('.')
                .append(introspectedColumn.getActualColumnName());

        sb.append(", Type: ").append(introspectedColumn.getActualTypeName());
        // append length for tinyint, char, varchar
        if (Types.CHAR == introspectedColumn.getJdbcType() ||
                Types.VARCHAR == introspectedColumn.getJdbcType() ||
                Types.TINYINT == introspectedColumn.getJdbcType()) {
            sb.append("(").append(introspectedColumn.getLength()).append(")");
        }

        String defaultVal = introspectedColumn.getDefaultValue().orElse(null);
        if (StringUtil.stringHasValue(defaultVal)) {
            sb.append(", Default value: ").append(defaultVal);
        }

        String remarks = introspectedColumn.getRemarks().orElse(null);
        if (StringUtil.stringHasValue(remarks)) {
            sb.append(", Remark: ").append(remarks.replace('\n', ' '));
        }

        return sb.toString();
    }

    // Escape so the comment can be embedded safely in the annotation source string literal.
    private String escape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\r", " ").replace("\n", " ");
    }
}
